[functions.get-vapid-key]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.check-fcm-config]
verify_jwt = false

[functions.mark-as-paid]
verify_jwt = false
